name: E2E on Chrome
on:
 push:
  branches:
    - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          start: npm start
